package main

import (
	"flag"
	"fmt"
	"html"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"wijnberg.net/vsdx-go/internal/renderpage"
	"wijnberg.net/vsdx-go/vsdx"
)

type CompareResult struct {
	Name      string
	GoldenSVG string
	NewSVG    string
	NewErr    string
}

func main() {
	inputDir := flag.String("input", "vsdx-svg", "directory with VSDX/SVG pairs")
	outputDir := flag.String("output", "render-compare-output", "output directory")
	flag.Parse()

	// Create output directory
	if err := os.MkdirAll(*outputDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output dir: %v\n", err)
		os.Exit(1)
	}

	// Find all VSDX files
	vsdxFiles, err := filepath.Glob(filepath.Join(*inputDir, "*.vsdx"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error finding VSDX files: %v\n", err)
		os.Exit(1)
	}

	var results []CompareResult

	for _, vsdxPath := range vsdxFiles {
		baseName := strings.TrimSuffix(filepath.Base(vsdxPath), ".vsdx")
		svgPath := filepath.Join(*inputDir, baseName+".svg")

		// Check if golden SVG exists
		if _, err := os.Stat(svgPath); os.IsNotExist(err) {
			fmt.Printf("Skipping %s (no matching SVG)\n", baseName)
			continue
		}

		result := processFile(baseName, vsdxPath, svgPath)
		results = append(results, result)

		// Copy golden SVG to output
		goldenData, _ := os.ReadFile(svgPath)
		os.WriteFile(filepath.Join(*outputDir, baseName+"_golden.svg"), goldenData, 0644)

		// Write rendered SVG
		if result.NewErr == "" {
			os.WriteFile(filepath.Join(*outputDir, baseName+"_rendered.svg"), []byte(result.NewSVG), 0644)
		}

		fmt.Printf("Processed: %s\n", baseName)
	}

	// Write HTML comparison
	htmlPath := filepath.Join(*outputDir, "compare.html")
	if err := writeHTML(results, htmlPath); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing HTML: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("\nOutput written to: %s/\n", *outputDir)
}

// extractPageNumber parses the golden SVG to find which page it was exported from.
// Returns 0-based index. Defaults to 0 if not found.
func extractPageNumber(goldenSVG string) int {
	// Look for "Page-N" in Visio's SVG comment: <!-- Generated by Microsoft Visio, SVG Export ... Page-2 -->
	re := regexp.MustCompile(`Page-(\d+)`)
	matches := re.FindStringSubmatch(goldenSVG)
	if len(matches) >= 2 {
		var pageNum int
		fmt.Sscanf(matches[1], "%d", &pageNum)
		return pageNum - 1 // Convert to 0-based index
	}
	return 0
}

func processFile(name, vsdxPath, svgPath string) CompareResult {
	result := CompareResult{Name: name}

	// Load golden SVG
	goldenData, err := os.ReadFile(svgPath)
	if err != nil {
		result.GoldenSVG = fmt.Sprintf("Error: %v", err)
	} else {
		result.GoldenSVG = string(goldenData)
	}

	// Load VSDX
	vf, err := vsdx.Open(vsdxPath)
	if err != nil {
		result.NewErr = fmt.Sprintf("VSDX load error: %v", err)
		return result
	}
	defer vf.Close()

	if len(vf.Pages) == 0 {
		result.NewErr = "No pages in VSDX"
		return result
	}

	// Determine which page to render based on golden SVG
	pageIndex := extractPageNumber(result.GoldenSVG)
	if pageIndex >= len(vf.Pages) {
		pageIndex = 0
	}
	page := vf.Pages[pageIndex]
	pageW := page.Width()
	pageH := page.Height()
	if pageW == 0 {
		pageW = 800
	}
	if pageH == 0 {
		pageH = 600
	}

	// Render with RenderTree renderer (shared with cmd/mutation-corpus-gen).
	newSVG, newErr := renderpage.Render(page, pageW, pageH)
	if newErr != nil {
		result.NewErr = newErr.Error()
	} else {
		result.NewSVG = newSVG
	}

	return result
}

func writeHTML(results []CompareResult, path string) error {
	var sb strings.Builder

	sb.WriteString(`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>VSDX Renderer Comparison</title>
<style>
body {
	font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
	margin: 0;
	padding: 20px;
	background: #f5f5f5;
}
h1 { margin: 0 0 10px; }
p.subtitle { color: #666; margin: 0 0 20px; }
.fixture {
	background: white;
	border-radius: 8px;
	padding: 20px;
	margin-bottom: 20px;
	box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}
.fixture-name {
	font-size: 18px;
	font-weight: 600;
	margin: 0 0 15px;
}
.compare-grid {
	display: grid;
	grid-template-columns: repeat(2, 1fr);
	gap: 15px;
}
.svg-panel {
	border: 1px solid #ddd;
	border-radius: 4px;
	overflow: hidden;
}
.svg-panel-header {
	padding: 8px 12px;
	border-bottom: 1px solid #ddd;
	font-weight: 500;
	font-size: 14px;
}
.svg-panel-header.golden { background: #e8f5e9; color: #2e7d32; }
.svg-panel-header.rendered { background: #e3f2fd; color: #1565c0; }
.svg-container {
	padding: 10px;
	background: white;
	min-height: 400px;
	overflow: auto;
}
.svg-container svg {
	width: 100%;
	height: auto;
}
.svg-container object {
	width: 100%;
	height: 500px;
}
.error {
	color: #c62828;
	padding: 10px;
	background: #ffebee;
	font-family: monospace;
	font-size: 12px;
}
</style>
</head>
<body>
<h1>VSDX Renderer Comparison</h1>
<p class="subtitle">Golden (Visio export) vs vsdx-go RenderTree</p>
`)

	for _, r := range results {
		sb.WriteString(fmt.Sprintf(`<div class="fixture">
<h2 class="fixture-name">%s</h2>
<div class="compare-grid">
`, html.EscapeString(r.Name)))

		// Golden panel - use object tag to load external SVG
		sb.WriteString(fmt.Sprintf(`<div class="svg-panel">
<div class="svg-panel-header golden">Golden (Visio)</div>
<div class="svg-container">
<object type="image/svg+xml" data="%s_golden.svg">Golden SVG</object>
</div>
</div>
`, r.Name))

		// Rendered panel
		sb.WriteString(`<div class="svg-panel">
<div class="svg-panel-header rendered">vsdx-go</div>
<div class="svg-container">
`)
		if r.NewErr != "" {
			sb.WriteString(fmt.Sprintf(`<div class="error">%s</div>`, html.EscapeString(r.NewErr)))
		} else {
			sb.WriteString(fmt.Sprintf(`<object type="image/svg+xml" data="%s_rendered.svg">Rendered SVG</object>`, r.Name))
		}
		sb.WriteString(`</div></div>
`)

		sb.WriteString(`</div></div>
`)
	}

	sb.WriteString(`</body></html>`)

	return os.WriteFile(path, []byte(sb.String()), 0644)
}
